### ISSUE TITLE
這些控件很美觀，希望能改進一下

### ISSUE THREAD

**Issue by Nu-est** [HuJinguang/CxFlatUI#5]
想把控件風格加入Attribute Theme，
仿效 Bootstrap 一樣有樣式主題等，
不知道這個主意如何？

**Comment by HuJinguang** [comment]
这是个很棒的主意，目前控件样式仿照的ElementUI[http://element-cn.eleme.io/#/zh-CN] ,该控件库完善后可能会加入其他风格样式
