### ISSUE TITLE
感谢，很漂亮，请问

### ISSUE THREAD

**Issue by jzlhll** [HuJinguang/CxFlatUI#8]
感谢，很漂亮，请问，能否在ThemeColor里面，增加给出预设的几套主题色。比如浅蓝色（默认这一套Color），再来几套。

**Comment by jzlhll** [comment]
我自己定制了。

**Comment by HuJinguang** [comment]
![TIM截图20190403000405](https://user-images.githubusercontent.com/22621198/55417884-1feaf480-55a4-11e9-8146-603f1464f59e.png)
可以通过改变ThemeColors.PrimaryColor来改变主题，
